name: test-pipeline
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SANDBOX_ACCESS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SANDBOX_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_SANDBOX_ACCOUNT_ID }}
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: TS build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14"
      - run: yarn
      - run: yarn build
  integration-tests:
    runs-on: ubuntu-latest
    name: Create Infrastructure & Integration Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14"
      - run: yarn
      - run: yarn aws-setup
      - run: yarn infra:up
      - run: yarn test:integration

  shutdown-stack:
    if: "always()"
    needs: integration-tests
    runs-on: ubuntu-latest
    name: Destroy Test Infrastructure
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14"
      - run: yarn
      - run: yarn aws-setup
      - run: yarn infra:destroy
